# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53ec5905128bcb1b14271a1e91748eaa4bd133c21b241910b21fbe7c879cd146a8f5827fd36f48966ff1b422ba819a1e66ed6a077673159dcc84d5416918e568

test:
  secret_key_base: 83005f52154c99592de1c88f85a499fec847e33a4644f386e2e56de35b89f466476d82c0205184971f5570419ed8c2baccf2471978224ade2223f9a77294325f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
